---
openapi: 3.1.0
info:
  title: My API
  description: My API description
  version: 0.1.0

servers:
  - url: http://localhost:3000/api
    description: Local server

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    Thing:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
      required:
        - name
        - quantity

paths:
  /stuff/{thingId}:
    get:
      operationId: GetThing
      summary: Get a thing
      description: |
        Get a thing from the database (this is in markdown)
      parameters:
        - name: thingId
          in: path
          required: true
          description: The ID of the thing to get
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Thing"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
