---
name: PR checks

"on":
  push:
    branches-ignore:
      - trunk
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gather:
    name: Gather information
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.workflows.outputs.workflows }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check yaml
        run: |
          yamllint -s .
      - name: Get workflows
        id: workflows
        run: |
          (printf "workflows=" && .github/bin/workflows.json.sh) >>"$GITHUB_OUTPUT"

  elm+npm:
    needs: gather
    if: "${{ contains(fromJson(needs.gather.outputs.workflows), 'elm+npm') }}"
    uses: ./.github/workflows/ci-elm+npm.yaml
