---
name: PR checks

"on":
  push:
    branches-ignore:
      - trunk
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gather:
    name: Gather information
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.workflows.outputs.workflows }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check yaml
        run: |
          yamllint -s .
      - name: Get workflows
        id: workflows
        run: |
          git remote set-head origin -a
          git fetch --depth=0 origin "${{ github.event.repository.default_branch }}":"${{ github.event.repository.default_branch }}"
          (
            printf "workflows=" &&
            .github/bin/workflows.json.sh "${{ github.event.repository.default_branch }}"
          ) >>"$GITHUB_OUTPUT"

  elm_npm:
    needs: gather
    if: "${{ contains(fromJson(needs.gather.outputs.workflows), 'elm+npm') }}"
    uses: ./.github/workflows/ci-elm+npm.yaml
